# Generated by Django 2.2.4 on 2019-08-29 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='科室大类')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '科室大类',
                'verbose_name_plural': '科室大类',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=200, verbose_name='医院')),
                ('title', models.CharField(default='20**年报告', max_length=80, unique=True, verbose_name='标题')),
                ('report_num', models.CharField(max_length=20, verbose_name='体检编号')),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=5, verbose_name='性别')),
                ('age', models.IntegerField(default='0', verbose_name='年龄')),
                ('work_unit', models.CharField(default='南京证券吴江营业部', max_length=20, verbose_name='工作单位')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='体检日期')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '体检报告',
                'verbose_name_plural': '体检报告',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小结内容')),
                ('doctor', models.CharField(max_length=80, verbose_name='小结医生')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Category', verbose_name='所属科室')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report', verbose_name='所属报告')),
            ],
            options={
                'verbose_name': '小结',
                'verbose_name_plural': '小结',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('check_results', models.TextField(verbose_name='检查结果')),
                ('unit', models.CharField(blank=True, max_length=10, verbose_name='单位')),
                ('reference_range', models.CharField(blank=True, max_length=20, verbose_name='参考范围')),
                ('tips', models.CharField(blank=True, choices=[('↑', '↑'), ('↓', '↓')], max_length=10, verbose_name='提示')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Category', verbose_name='科室')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report', verbose_name='所属报告')),
            ],
            options={
                'verbose_name': '检查项目',
                'verbose_name_plural': '检查项目',
            },
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(verbose_name='综述')),
                ('proposal', models.TextField(verbose_name='建议')),
                ('summary_doctor', models.CharField(max_length=5, verbose_name='总检医生')),
                ('summary_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='总检日期')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.Report', verbose_name='所属报告')),
            ],
            options={
                'verbose_name': '总检结论',
                'verbose_name_plural': '总检结论',
            },
        ),
    ]
