# Generated by Django 2.2.4 on 2019-08-14 01:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=200, verbose_name='医院')),
                ('title', models.CharField(default='20**年报告', max_length=80, verbose_name='标题')),
                ('report_num', models.CharField(max_length=20, verbose_name='体检编号')),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('boy', '男'), ('girl', '女')], default='boy', max_length=5, verbose_name='性别')),
                ('age', models.IntegerField(default='0', verbose_name='年龄')),
                ('work_unit', models.CharField(default='南京证券吴江营业部', max_length=20, verbose_name='工作单位')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='体检日期')),
            ],
            options={
                'verbose_name_plural': '体检报告信息',
                'verbose_name': '体检报告信息',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('内科', '内科'), ('血压', '血压'), ('心电图', '心电图'), ('彩超', '彩超'), ('放射科', '放射科'), ('血常规', '血常规'), ('生化', '生化'), ('免疫', '免疫'), ('肿瘤', '肿瘤')], default='内科', max_length=80, verbose_name='所属科室')),
                ('content', models.TextField(verbose_name='小结内容')),
                ('doctor', models.CharField(max_length=80, verbose_name='小结医生')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report', verbose_name='所属报告')),
            ],
            options={
                'verbose_name_plural': '小结',
                'verbose_name': '小结',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('内科', '内科'), ('血压', '血压'), ('心电图', '心电图'), ('彩超', '彩超'), ('放射科', '放射科'), ('血常规', '血常规'), ('生化', '生化'), ('免疫', '免疫'), ('肿瘤', '肿瘤')], default='内科', max_length=80, verbose_name='科室')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('check_results', models.TextField(verbose_name='检查结果')),
                ('unit', models.CharField(blank=True, max_length=10, verbose_name='单位')),
                ('reference_range', models.CharField(blank=True, max_length=20, verbose_name='参考范围')),
                ('tips', models.CharField(blank=True, max_length=10, verbose_name='提示')),
                ('report', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.Report', verbose_name='所属报告')),
            ],
            options={
                'verbose_name_plural': '具体检查项目',
                'verbose_name': '具体检查项目',
            },
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(verbose_name='综述')),
                ('proposal', models.TextField(verbose_name='建议')),
                ('summary_doctor', models.CharField(max_length=5, verbose_name='总检医生')),
                ('summary_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='总检日期')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report', verbose_name='所属报告')),
            ],
            options={
                'verbose_name_plural': '总检结论',
                'verbose_name': '总检结论',
            },
        ),
    ]
