# Generated by Django 2.2.4 on 2019-08-14 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': '检查项目', 'verbose_name_plural': '检查项目'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-date',), 'verbose_name': '体检报告', 'verbose_name_plural': '体检报告'},
        ),
    ]
