# Generated by Django 2.2.4 on 2019-08-16 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190814_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('无可选项', '无可选项'), ('内科', '内科'), ('血压', '血压'), ('心电图', '心电图'), ('血常规', '血常规'), ('尿常规', '尿常规'), ('彩超', '彩超'), ('胸部CT', '胸部CT'), ('甲状腺彩超', '甲状腺彩超'), ('血糖', '血糖'), ('血脂4项', '血脂4项'), ('肾功能4项', '肝功能7项'), ('肿瘤常规', '肿瘤常规')], default='无可选项', max_length=200, verbose_name='科室大类')),
                ('name_w', models.CharField(max_length=200, verbose_name='科室大类')),
            ],
            options={
                'verbose_name': '科室大类',
                'verbose_name_plural': '科室大类',
            },
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Category', verbose_name='科室'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report', verbose_name='所属报告'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Category', verbose_name='所属科室'),
        ),
    ]
