# Generated by Django 2.2.4 on 2019-08-16 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190816_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_w',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='科室大类'),
        ),
        migrations.AlterField(
            model_name='conclusion',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report', unique=True, verbose_name='所属报告'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(default='20**年报告', max_length=80, unique=True, verbose_name='标题'),
        ),
    ]
