# Generated by Django 2.2.4 on 2019-08-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20190816_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclusion',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.Report', verbose_name='所属报告'),
        ),
    ]
