# Generated by Django 2.2.4 on 2019-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20190816_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tips',
            field=models.CharField(choices=[('', ''), ('up', '↑'), ('down', '↓')], default='', max_length=10, verbose_name='提示'),
        ),
    ]
