# Generated by Django 2.2.4 on 2019-08-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20190816_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tips',
            field=models.CharField(blank=True, choices=[('up', '↑'), ('down', '↓')], max_length=10, verbose_name='提示'),
        ),
    ]
