# Generated by Django 2.2.4 on 2019-08-17 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20190816_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Category', verbose_name='科室'),
        ),
    ]
