# Generated by Django 2.2.4 on 2019-08-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20190817_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=5, verbose_name='性别'),
        ),
    ]
